image: node:12.18.3

pipelines:
  default:
    - step:
        caches:
          - node
          - backendnode
          - webappnode
          - blockchainnode
        script:
          - cd ./webapp 
          - yarn install --unsafe-perm
          - yarn run build
          - yarn run linters-ci
          - cd ../blockchain
          - yarn install --unsafe-perm
          - yarn run linters-ci
          - yarn run truffle:deploy:test
          - yarn run truffle:compile
definitions:
  caches:
    backendnode: backend/node_modules
    webappnode: webapp/node_modules
    blockchainnode: blockchain/node_modules
