image: node:10.16.0

pipelines:
  default:
    - step:
        caches:
          - node
          - backendnode
          - webappnode
          - blockchainnode
        script:
          - cd ./webapp 
          - npm install --unsafe-perm
          - npm run build
          - npm run linters-ci
          - cd ../blockchain
          - npm install
          - npm run truffle:compile
          - npm run truffle:deploy:test
definitions:
  caches:
    backendnode: backend/node_modules
    webappnode: webapp/node_modules
    blockchainnode: blockchain/node_modules
