image: node:12

pipelines:
  default:
    - step:
        caches:
          - node
          - backendnode
          - webappnode
          - blockchainnode
        script:
          - cd ./webapp 
          - yarn
          - yarn build
          - yarn linters-ci
          - cd ../blockchain
          - yarn
          - yarn linters-ci
          - yarn truffle:deploy:test
          - yarn truffle:compile
          - cd ../backend
          - yarn
          - yarn build
          - yarn linters-ci
definitions:
  caches:
    backendnode: backend/node_modules
    webappnode: webapp/node_modules
    blockchainnode: blockchain/node_modules
